language: crystal

# Uncomment the following if you'd like Travis to run specs and check code formatting

crystal:
  - latest
  - nightly

jobs:
  allow_failures:
    - crystal: nightly

before_install:
  - sudo apt-get -y install libgit2-dev libgit2-24
addons:
  apt:
    update: true

script:
  - crystal spec
#   - crystal tool format --check
